### ISSUE TITLE
Enum duplication.

### ISSUE THREAD

**Issue by rizkovs1149** [sugar-cubes/sugar-cubes-cloner#1]
`Cloners.reflection()` creates duplicate enum instance when enum constant defines a body.
```java
enum MyEnum {
  X {};
}
```
Then `Cloners.reflection().clone(MyEnum.X) != MyEnum.X`.
Expected `Cloners.reflection().clone(MyEnum.X) == MyEnum.X`.

**Comment by mbutov** [comment]
Fixed in 1.1.0

**Comment by mbutov** [comment]
Fixed in 1.1.0
